-- Filmova databaze

UPDATE STATISTICS Users;
UPDATE STATISTICS Movies;
UPDATE STATISTICS CastAndCrew;
UPDATE STATISTICS Genres;
UPDATE STATISTICS Ratings;
UPDATE STATISTICS FavoriteMovies;
UPDATE STATISTICS Reviews;