-- Filmova databaze

UPDATE STATISTICS Directors;
UPDATE STATISTICS Actors;
UPDATE STATISTICS Genres;
UPDATE STATISTICS Movies;
UPDATE STATISTICS Ratings;
UPDATE STATISTICS FavoriteMovies;
UPDATE STATISTICS Reviews;
UPDATE STATISTICS Users;